# Generated by Django 2.1.5 on 2019-02-06 21:41

from django.db import migrations, models
import game_store.apps.purchases.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('S', 'Succeeded'), ('F', 'Failed')], default=game_store.apps.purchases.models.TransactionStatus('F'), max_length=1),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
