# Generated by Django 2.1.5 on 2019-02-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gamestate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestate',
            old_name='player',
            new_name='user',
        ),
    ]
