# Generated by Django 2.1.5 on 2019-02-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20190213_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='game_state',
            field=models.TextField(),
        ),
    ]
